apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* "^/swagger-ui(/|$)") {
        add_header Cache-Control "no-store" always;
      }
      if ($request_uri ~* "^/api-docs(/|$)") {
        add_header Cache-Control "no-store" always;
      }
spec:
  rules:
  - host: goormthon-5.goorm.training #FIXME:
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /api-docs
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
