server:
  port: 8080
  forward-headers-strategy: framework

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  web:
    resources:
      cache:
        cachecontrol:
          no-store: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - https://goormthon-5.goorm.training
      - http://goormthon-5.goorm.training
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    exposed-headers:
      - Location
    allow-credentials: true
    max-age: 3600
